demo_dbt:
  #target: dev
  outputs:
    dev:
      account: pga76060.east-us-2.azure.snowflakecomputing.com
      database: SNOW_DBT_POSTGRE
      password: '@OQRbh;O/89OI$L#'
      role: ACCOUNTADMIN
      schema: TRUSTED
      threads: 1
      host: pga76060.east-us-2.azure.snowflakecomputing.com
      type: snowflake
      user: POCDDDBTAPP
      warehouse: COMPUTE_WH

  target: dev